version: '3'

services:

  database:
    image: 'mongo:6.0'
    container_name: "mongodb"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
  fname:
    image: 'fname:1.0'
    container_name: "fname"
    ports:
      - 8080:8080
    links:
      - mname
      - database
  mname:
    image: 'mname:1.0'
    container_name: "mname"
    ports:
      - 8082:8082
    links:
      - lname
      - database
  lname:
    image: 'lname:1.0'
    container_name: "lname"
    ports:
      - 8083:8083
    links:
      - database
