version: '3.8'
services:

  db:
     image: mongo:5.0
     container_name: mongodb-f
     restart: on-failure
     ports:
       - 27017:27017
     networks:
       - net1

  MIC1:
     image: first-name-f
     container_name: fName
     build: ./firstName
     environment:
       - MONGO_URL=mongodb://admin:password@localhost:27017/?authSource=admin&authMechanism=SCRAM-SHA-256
     restart: on-failure
     depends_on:
       - db
     ports:
       - 8080:8080
     networks:
       - net1

  MIC2:
     image: middle-name-f
     container_name: mName
     build: ./middleName
     environment:
       - MONGO_URL=mongodb://admin:password@localhost:27017/?authSource=admin&authMechanism=SCRAM-SHA-256
     restart: on-failure
     depends_on:
       - MIC1
     expose:
       - "8082"
     networks:
       - net1

  MIC3:
     image: last-name-f
     container_name: lName
     build: ./lastName
     environment:
       - MONGO_URL=mongodb://admin:password@localhost:27017/?authSource=admin&authMechanism=SCRAM-SHA-256
     restart: on-failure
     depends_on:
       - MIC2
     expose:
       - "8083"
     networks:
       - net1

networks:
  net1:
     driver: bridge
